apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:3.2.2
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "kong migrations bootstrap || kong migrations up"]
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: "postgres"
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_USER
              value: "kong"
            - name: KONG_PG_PASSWORD
              value: "password"
            - name: KONG_PG_DATABASE
              value: "kong"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
---
apiVersion: v1
kind: Service
metadata:
  name: kong-service
spec:
  selector:
    app: kong
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
      nodePort: 30080
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
      nodePort: 30443
    - name: admin
      port: 8001
      targetPort: 8001
      protocol: TCP
      nodePort: 30081
  type: NodePort
